require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'meliuzrnts' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    #:subspecs => [
    #  'Core',
    #  'RCTActionSheet',
    #  'RCTGeolocation',
    #  'RCTImage',
    #  'RCTLinkingIOS',
    #  'RCTNetwork',
    #  'RCTSettings',
    #  'RCTText',
    #  'RCTVibration',
    #  'RCTWebSocket'
    #]
  )

  # when not using frameworks  we can do this instead of including the source files in our project (1/4):
  # pod 'react-native-maps', path: '../../'
  #	pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS

  # when not using frameworks  we can remove this line (2/4):
   # pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  

  target 'meliuzrntsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end